# Starship Configuration File

# Directory
[directory]
truncation_length = 16
style = "italic blue"

# Time
[time]
disabled = false
format = "[$time]($style) "
time_format = "🕙[%T]"

# Username
[username]
format = "[$user]($style)@"
style_root = "bold bg:red fg:black"
style_user = "bold red"
show_always = true

# Hostname
[hostname]
ssh_only = false
style = "bold cyan"
